version: "3"
services:
   web:
      image: hacklab/mapasculturais-nginx:latest
      volumes:
         - ./docker-data/public-files:/var/www/html/files
         - ./docker-data/assets:/var/www/html/assets

         # to prevent 404
         - /dev/null:/var/www/html/index.php
      ports:
         - "8080:80"
         - "8443:443"
      depends_on:
         - mapasculturais
      links:
         - mapasculturais

   mapasculturais:
      image: mapasculturais/mapasculturais:latest
      ports:
         - "9000:9000"
      volumes:
         - ./docker-data/assets:/var/www/html/assets
         - ./docker-data/public-files:/var/www/html/files
         - ./docker-data/private-files:/var/www/private-files
      links:
         - db
      environment:
         - POSTGRES_PASSWORD=mapas
         - POSTGRES_USER=mapas
         - POSTGRES_DB=mapas

         #      - APP_LCODE=pt_BR,es_ES # para selecao do idioma baseado no navegador
         - APP_LCODE=pt_BR

         - APP_MODE=production

         #      - ACTIVE_THEME=SpCultura

         - PENDING_PCACHE_RECREATION_INTERVAL=60

      depends_on:
         - db

   db:
      image: mdillon/postgis:11
      environment:
         - POSTGRES_PASSWORD=mapas
         - POSTGRES_USER=mapas
         - POSTGRES_DB=mapas
         - POSTGRES_DB_TEST=mapasculturais_test
      ports:
         - "5435:5432"
      volumes:
         - docker-data:/var/lib/postgresql/data
         - ./db/schema.sql:/docker-entrypoint-initdb.d/0.schema.sql
         - ./db/initial-data.sql:/docker-entrypoint-initdb.d/1.data.sql
volumes:
   docker-data:
