version: '2'
services:
  mapas:
    build:
      context: ../
      dockerfile: compose/local/Dockerfile
    ports:
      - "8080:80"
    volumes:
      - ../src/protected:/var/www/html/protected
      - ../scripts:/var/www/scripts
      - ../compose/config.php:/var/www/html/protected/application/conf/config.php
      - ../compose/config.d:/var/www/html/protected/application/conf/config.d
      - ../compose/local/config.local.php:/var/www/html/protected/application/conf/config.d/z.config.local.php
      - ../docker-data/assets:/var/www/html/assets
      - ../docker-data/public-files:/var/www/html/files
      - ../docker-data/private-files:/var/www/private-files
      - ../docker-data/pcache-cron.log:/var/www/scripts/nohup.out
      - ../tests:/var/www/tests
    links:
      - db
    environment:
      # - DB_HOST=db
      # - DB_NAME=mapas
      # - DB_USER=mapas
      # - DB_PASS=mapas

      - APP_LCODE=pt_BR,es_ES
      - ACTIVE_THEME=Ceara
      - APP_MODE=development

    depends_on:
      - db
      
    stdin_open: true
    tty: true
      
  db:
    image: mdillon/postgis:11
    environment:
      - POSTGRES_PASSWORD=mapas
      - POSTGRES_USER=mapas
      - POSTGRES_DB=mapas
    ports:
      - "5435:5432"
    volumes:
      - docker-data:/var/lib/postgresql/data
      - ../db/schema.sql:/docker-entrypoint-initdb.d/0.schema.sql
      - ../db/initial-data.sql:/docker-entrypoint-initdb.d/1.data.sql

volumes:
   docker-data: